
export const OWNERDIC_SELECT = "OWNERDIC_SELECT";
export const OWNERDIC_CREATE = "OWNERDIC_CREATE";
export const OWNERDIC_UPDATE = "OWNERDIC_UPDATE";
export const OWNERDIC_DELETE = "OWNERDIC_DELETE";

export const AGENTDIC_SELECT = "AGENTDIC_SELECT";
export const AGENTDIC_CREATE = "AGENTDIC_CREATE";
export const AGENTDIC_UPDATE = "AGENTDIC_UPDATE";
export const AGENTDIC_DELETE = "AGENTDIC_DELETE";

export const OBJDIC_SELECT = "OBJDIC_SELECT";
export const OBJDIC_CREATE = "OBJDIC_CREATE";
export const OBJDIC_UPDATE = "OBJDIC_UPDATE";
export const OBJDIC_DELETE = "OBJDIC_DELETE";

export const DOGDIC_SELECT = "DOGDIC_SELECT";
export const DOGDIC_CREATE = "DOGDIC_CREATE";
export const DOGDIC_UPDATE = "DOGDIC_UPDATE";
export const DOGDIC_DELETE = "DOGDIC_DELETE";

export const YURLITSO = "YURLITSO";
export const DOGOVOR_TYPE = "DOGOVOR_TYPE";
export const VARIABLE = "VARIABLE";
export const FORM_DATA_NEW = "FORM_DATA_NEW";
export const DOGOVOR_DATA = "DOGOVOR_DATA";
export const ZAKAZCHIK_TYPEONE_DATA = "ZAKAZCHIK_TYPEONE_DATA";
export const ZAKAZCHIK_TYPETWO_DATA = "ZAKAZCHIK_TYPETWO_DATA";
export const ZAKAZCHIK_TYPETHREE_DATA = "ZAKAZCHIK_TYPETHREE_DATA";

export const FETCH_SAMPLE_STARTED = "FETCH_SAMPLE_STARTED";
export const FETCH_SAMPLE_SUCCESS = 'FETCH_SAMPLE_SUCCESS';
export const FETCH_SAMPLE_FAILED = 'FETCH_SAMPLE_FAILED';

// API actions
// GET
  export const GET_OWNER_STARTED = "GET_OWNER_STARTED";
  export const GET_OWNER_SUCCESS = "GET_OWNER_SUCCESS";
  export const GET_OWNER_FAILED = "GET_OWNER_FAILED";
// POST
  export const POST_OWNER_STARTED = "POST_OWNER_STARTED";
  export const POST_OWNER_SUCCESS = "POST_OWNER_SUCCESS";
  export const POST_OWNER_FAILED = "POST_OWNER_FAILED";
// PUT
  export const PUT_OWNER_STARTED = "PUT_OWNER_STARTED";
  export const PUT_OWNER_SUCCESS = "PUT_OWNER_SUCCESS";
  export const PUT_OWNER_FAILED = "PUT_OWNER_FAILED";
// DELETE
  export const DELETE_OWNER_STARTED = "DELETE_OWNER_STARTED";
  export const DELETE_OWNER_SUCCESS = "DELETE_OWNER_SUCCESS";
  export const DELETE_OWNER_FAILED = "DELETE_OWNER_FAILED";



