
export const OWNERDIC_SELECT = "OWNERDIC_SELECT";
export const OWNERDIC_CREATE = "OWNERDIC_CREATE";
export const OWNERDIC_UPDATE = "OWNERDIC_UPDATE";
export const OWNERDIC_DELETE = "OWNERDIC_DELETE";
export const AGENTDIC_SELECT = "AGENTDIC_SELECT";
export const AGENTDIC_CREATE = "AGENTDIC_CREATE";
export const AGENTDIC_UPDATE = "AGENTDIC_UPDATE";
export const AGENTDIC_DELETE = "AGENTDIC_DELETE";
export const OBJDIC_SELECT = "OBJDIC_SELECT";
export const OBJDIC_CREATE = "OBJDIC_CREATE";
export const OBJDIC_UPDATE = "OBJDIC_UPDATE";
export const OBJDIC_DELETE = "OBJDIC_DELETE";
export const DOGDIC_SELECT = "DOGDIC_SELECT";
export const DOGDIC_CREATE = "DOGDIC_CREATE";
export const DOGDIC_UPDATE = "DOGDIC_UPDATE";
export const DOGDIC_DELETE = "DOGDIC_DELETE";

export const YURLITSO = "YURLITSO";
export const DOGOVOR_TYPE = "DOGOVOR_TYPE";
export const VARIABLE = "VARIABLE";
export const FORM_DATA_NEW = "FORM_DATA_NEW";
export const DOGOVOR_DATA = "DOGOVOR_DATA";
export const ZAKAZCHIK_TYPEONE_DATA = "ZAKAZCHIK_TYPEONE_DATA";
export const ZAKAZCHIK_TYPETWO_DATA = "ZAKAZCHIK_TYPETWO_DATA";
export const ZAKAZCHIK_TYPETHREE_DATA = "ZAKAZCHIK_TYPETHREE_DATA";

export const FETCH_SAMPLE_STARTED = "FETCH_SAMPLE_STARTED";
export const FETCH_SAMPLE_SUCCESS = 'FETCH_SAMPLE_SUCCESS';
export const FETCH_SAMPLE_FAILED = 'FETCH_SAMPLE_FAILED';

// OWNER
  export const GET_OWNER_STARTED = "GET_OWNER_STARTED";
  export const GET_OWNER_SUCCESS = "GET_OWNER_SUCCESS";
  export const GET_OWNER_FAILED = "GET_OWNER_FAILED";
  export const POST_OWNER_STARTED = "POST_OWNER_STARTED";
  export const POST_OWNER_SUCCESS = "POST_OWNER_SUCCESS";
  export const POST_OWNER_FAILED = "POST_OWNER_FAILED";
  export const PUT_OWNER_STARTED = "PUT_OWNER_STARTED";
  export const PUT_OWNER_SUCCESS = "PUT_OWNER_SUCCESS";
  export const PUT_OWNER_FAILED = "PUT_OWNER_FAILED";
  export const DELETE_OWNER_STARTED = "DELETE_OWNER_STARTED";
  export const DELETE_OWNER_SUCCESS = "DELETE_OWNER_SUCCESS";
  export const DELETE_OWNER_FAILED = "DELETE_OWNER_FAILED";
// AGENT
  export const GET_AGENT_STARTED = "GET_AGENT_STARTED";
  export const GET_AGENT_SUCCESS = "GET_AGENT_SUCCESS";
  export const GET_AGENT_FAILED = "GET_AGENT_FAILED";
  export const POST_AGENT_STARTED = "POST_AGENT_STARTED";
  export const POST_AGENT_SUCCESS = "POST_AGENT_SUCCESS";
  export const POST_AGENT_FAILED = "POST_AGENT_FAILED";
  export const PUT_AGENT_STARTED = "PUT_AGENT_STARTED";
  export const PUT_AGENT_SUCCESS = "PUT_AGENT_SUCCESS";
  export const PUT_AGENT_FAILED = "PUT_AGENT_FAILED";
  export const DELETE_AGENT_STARTED = "DELETE_AGENT_STARTED";
  export const DELETE_AGENT_SUCCESS = "DELETE_AGENT_SUCCESS";
  export const DELETE_AGENT_FAILED = "DELETE_AGENT_FAILED";
// OBJECT
  export const GET_OBJECT_STARTED = "GET_OWNER_STARTED";
  export const GET_OBJECT_SUCCESS = "GET_OWNER_SUCCESS";
  export const GET_OBJECT_FAILED = "GET_OWNER_FAILED";
  export const POST_OBJECT_STARTED = "POST_OWNER_STARTED";
  export const POST_OBJECT_SUCCESS = "POST_OWNER_SUCCESS";
  export const POST_OBJECT_FAILED = "POST_OWNER_FAILED";
  export const PUT_OBJECT_STARTED = "PUT_OWNER_STARTED";
  export const PUT_OBJECT_SUCCESS = "PUT_OWNER_SUCCESS";
  export const PUT_OBJECT_FAILED = "PUT_OWNER_FAILED";
  export const DELETE_OBJECT_STARTED = "DELETE_OWNER_STARTED";
  export const DELETE_OBJECT_SUCCESS = "DELETE_OWNER_SUCCESS";
  export const DELETE_OBJECT_FAILED = "DELETE_OWNER_FAILED";

// DIC
  export const GET_DIC_STARTED = "GET_DIC_STARTED";
  export const GET_DIC_SUCCESS = "GET_DIC_SUCCESS";
  export const GET_DIC_FAILED = "GET_DIC_FAILED";
  export const POST_DIC_STARTED = "POST_DIC_STARTED";
  export const POST_DIC_SUCCESS = "POST_DIC_SUCCESS";
  export const POST_DIC_FAILED = "POST_DIC_FAILED";
  export const PUT_DIC_STARTED = "PUT_DIC_STARTED";
  export const PUT_DIC_SUCCESS = "PUT_DIC_SUCCESS";
  export const PUT_DIC_FAILED = "PUT_DIC_FAILED";
  export const DELETE_DIC_STARTED = "DELETE_DIC_STARTED";
  export const DELETE_DIC_SUCCESS = "DELETE_DIC_SUCCESS";
  export const DELETE_DIC_FAILED = "DELETE_DIC_FAILED";
